IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'SIMULACAO' AND TABLE_NAME = 'BANCO') 
	BEGIN
		CREATE TABLE SIMULACAO.BANCO (
			ID int IDENTITY(1,1) NOT NULL,
			CODIGO varchar(6) COLLATE Latin1_General_CI_AS NOT NULL,
			DESCRICAO varchar(250) COLLATE Latin1_General_CI_AS NOT NULL
			PRIMARY KEY CLUSTERED 
		(
			ID ASC
		)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
		)

	END