CREATE TABLE SIMULACAO.BANCO_AUDIT (
	REVISION_ID INTEGER NOT NULL,
	ID int NOT NULL,
	REVISION_TYPE int NOT NULL,
	CODIGO varchar(6) NOT NULL,
	DESCRICAO varchar(250) NOT NULL,
    	PRIMARY KEY (REVISION_ID , ID),
	CONSTRAINT `idfk_banco_revinfo_rev_id` FOREIGN KEY (REVISION_ID) REFERENCES REVISION_INFO (REVISION_ID)
);