CREATE TABLE SIMULACAO.MOVIMENTACAO (
			ID int NOT NULL PRIMARY KEY AUTO_INCREMENT,
			CONTA_FK int NOT NULL,
			DATA_MOVIMENTACAO datetime NOT NULL,
			TIPO_MOVIMENTACAO int NOT NULL,
			TIPO_LANCAMENTO int NOT NULL,
			VALOR decimal(19,5) NOT NULL,
			foreign key (CONTA_FK) references CONTA(ID))