INSERT INTO SIMULACAO.BANCO (CODIGO, DESCRICAO) VALUES('001', 'BANCO DO BRASIL');
INSERT INTO SIMULACAO.BANCO (CODIGO, DESCRICAO) VALUES('341', 'ITAÚ');
INSERT INTO SIMULACAO.BANCO (CODIGO, DESCRICAO) VALUES('104', 'CAIXA ECONÔMICA FEDERAL');
INSERT INTO SIMULACAO.BANCO (CODIGO, DESCRICAO) VALUES('033', 'SANTANDER');
INSERT INTO SIMULACAO.BANCO (CODIGO, DESCRICAO) VALUES('237', 'BRADESCO');