IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'SIMULACAO' AND TABLE_NAME = 'TRANSFERENCIA') 
	BEGIN
		CREATE TABLE SIMULACAO.TRANSFERENCIA (
			ID int IDENTITY(1,1) NOT NULL,
			CONTA_ORIGEM int NOT NULL,
			CONTA_DESTINO int NOT NULL,
			DATA_TRANSFERENCIA datetime NOT NULL,
			VALOR decimal(19,5) NOT NULL,
			TRANSFERIDO bit NOT NULL
			PRIMARY KEY CLUSTERED 
		(
			ID ASC
		)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
		)
		
		ALTER TABLE [SIMULACAO].[TRANSFERENCIA]  WITH CHECK ADD  CONSTRAINT [CNT_TRANSFERENCIA_CONTA_ORIGEM] FOREIGN KEY([CONTA_ORIGEM])
		REFERENCES [SIMULACAO].[CONTA] ([ID])

		ALTER TABLE [SIMULACAO].[TRANSFERENCIA] CHECK CONSTRAINT [CNT_TRANSFERENCIA_CONTA_ORIGEM]
		
		ALTER TABLE [SIMULACAO].[TRANSFERENCIA]  WITH CHECK ADD  CONSTRAINT [CNT_TRANSFERENCIA_CONTA_DESTINO] FOREIGN KEY([CONTA_DESTINO])
		REFERENCES [SIMULACAO].[CONTA] ([ID])

		ALTER TABLE [SIMULACAO].[TRANSFERENCIA] CHECK CONSTRAINT [CNT_TRANSFERENCIA_CONTA_DESTINO]

	END