CREATE TABLE SIMULACAO.TRANSFERENCIA (
			ID int NOT NULL AUTO_INCREMENT,
			CONTA_ORIGEM int NOT NULL,
			CONTA_DESTINO int NOT NULL,
			DATA_TRANSFERENCIA datetime NOT NULL,
			VALOR decimal(19,5) NOT NULL,
			TRANSFERIDO bit NOT NULL,
			foreign key (CONTA_ORIGEM) references CONTA(ID),
			foreign key (CONTA_DESTINO) references CONTA(ID))