DECLARE @idBanco INT
DECLARE @idConta INT

INSERT INTO SIMULACAO.BANCO (CODIGO, DESCRICAO) VALUES('001', 'BANCO DO BRASIL');
SET @idBanco = CAST(SCOPE_IDENTITY() as int)
INSERT INTO SIMULACAO.CONTA (AGENCIA, DIGITO_AGENCIA, NUMERO, DIGITO, BANCO_FK, TIPO_CONTA) VALUES ('4444', '4', '4444444444', '4', @idBanco, 1);
SET @idConta = CAST(SCOPE_IDENTITY() as int)
insert into SIMULACAO.MOVIMENTACAO (CONTA_FK, DATA_MOVIMENTACAO, TIPO_MOVIMENTACAO, TIPO_LANCAMENTO, VALOR) VALUES (@idConta, getDate(), 1, 3, 5000)

INSERT INTO SIMULACAO.BANCO (CODIGO, DESCRICAO) VALUES('341', 'ITAÚ');
SET @idBanco = CAST(SCOPE_IDENTITY() as int)
INSERT INTO SIMULACAO.CONTA (AGENCIA, DIGITO_AGENCIA, NUMERO, DIGITO, BANCO_FK, TIPO_CONTA) VALUES ('5555', '5', '5555555555', '5', @idBanco, 1);
SET @idConta = CAST(SCOPE_IDENTITY() as int)
insert into SIMULACAO.MOVIMENTACAO (CONTA_FK, DATA_MOVIMENTACAO, TIPO_MOVIMENTACAO, TIPO_LANCAMENTO, VALOR) VALUES (@idConta, getDate(), 1, 3, 5000)

INSERT INTO SIMULACAO.BANCO (CODIGO, DESCRICAO) VALUES('104', 'CAIXA ECONÔMICA FEDERAL');
SET @idBanco = CAST(SCOPE_IDENTITY() as int)
INSERT INTO SIMULACAO.CONTA (AGENCIA, DIGITO_AGENCIA, NUMERO, DIGITO, BANCO_FK, TIPO_CONTA) VALUES ('6666', '6', '6666666666', '6', @idBanco, 2);
SET @idConta = CAST(SCOPE_IDENTITY() as int)
insert into SIMULACAO.MOVIMENTACAO (CONTA_FK, DATA_MOVIMENTACAO, TIPO_MOVIMENTACAO, TIPO_LANCAMENTO, VALOR) VALUES (@idConta, getDate(), 1, 3, 5000)

INSERT INTO SIMULACAO.BANCO (CODIGO, DESCRICAO) VALUES('033', 'SANTANDER');
INSERT INTO SIMULACAO.BANCO (CODIGO, DESCRICAO) VALUES('237', 'BRADESCO');