IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'SIMULACAO' AND TABLE_NAME = 'MOVIMENTACAO') 
	BEGIN
		CREATE TABLE SIMULACAO.MOVIMENTACAO (
			ID int IDENTITY(1,1) NOT NULL,
			CONTA_FK int NOT NULL,
			DATA_MOVIMENTACAO datetime NOT NULL,
			TIPO_MOVIMENTACAO int NOT NULL,
			TIPO_LANCAMENTO int NOT NULL,
			VALOR decimal(19,5) NOT NULL
			PRIMARY KEY CLUSTERED 
		(
			ID ASC
		)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
		)
		
		ALTER TABLE [SIMULACAO].[MOVIMENTACAO]  WITH CHECK ADD  CONSTRAINT [CNT_MOVIMENTACAO_CONTA_FK] FOREIGN KEY([CONTA_FK])
		REFERENCES [SIMULACAO].[CONTA] ([ID])

		ALTER TABLE [SIMULACAO].[MOVIMENTACAO] CHECK CONSTRAINT [CNT_MOVIMENTACAO_CONTA_FK]

	END