IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'SIMULACAO' AND TABLE_NAME = 'CONTA') 
	BEGIN
		CREATE TABLE SIMULACAO.CONTA (
			ID int IDENTITY(1,1) NOT NULL,
			AGENCIA varchar(10) COLLATE Latin1_General_CI_AS NOT NULL,
			DIGITO_AGENCIA varchar(3) COLLATE Latin1_General_CI_AS NULL,
			NUMERO varchar(10) COLLATE Latin1_General_CI_AS NOT NULL,
			DIGITO varchar(3) COLLATE Latin1_General_CI_AS NOT NULL,
			BANCO_FK int NOT NULL,
			TIPO_CONTA int NOT NULL
			PRIMARY KEY CLUSTERED 
		(
			ID ASC
		)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
		)
		
		ALTER TABLE [SIMULACAO].[CONTA]  WITH CHECK ADD  CONSTRAINT [CNT_CONTA_BANCO_FK] FOREIGN KEY([BANCO_FK])
		REFERENCES [SIMULACAO].[BANCO] ([ID])

		ALTER TABLE [SIMULACAO].[CONTA] CHECK CONSTRAINT [CNT_CONTA_BANCO_FK]

	END